//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agent_SSO.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.WS_BCC_Autenticacao_UsuarioSoap")]
    public interface WS_BCC_Autenticacao_UsuarioSoap {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento sUser no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Autenticacao_Usuario", ReplyAction="*")]
        Agent_SSO.ServiceReference2.Autenticacao_UsuarioResponse Autenticacao_Usuario(Agent_SSO.ServiceReference2.Autenticacao_UsuarioRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento sCommand no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Registra_Tempo_Usuario", ReplyAction="*")]
        Agent_SSO.ServiceReference2.Registra_Tempo_UsuarioResponse Registra_Tempo_Usuario(Agent_SSO.ServiceReference2.Registra_Tempo_UsuarioRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento sText no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Criptografia", ReplyAction="*")]
        Agent_SSO.ServiceReference2.CriptografiaResponse Criptografia(Agent_SSO.ServiceReference2.CriptografiaRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento sCommand no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ping_Localizacao_Usuario", ReplyAction="*")]
        Agent_SSO.ServiceReference2.Ping_Localizacao_UsuarioResponse Ping_Localizacao_Usuario(Agent_SSO.ServiceReference2.Ping_Localizacao_UsuarioRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento sCommand no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Rel_Tempo_Usuario", ReplyAction="*")]
        Agent_SSO.ServiceReference2.Rel_Tempo_UsuarioResponse Rel_Tempo_Usuario(Agent_SSO.ServiceReference2.Rel_Tempo_UsuarioRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento sCommand no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Rota_Usuario", ReplyAction="*")]
        Agent_SSO.ServiceReference2.Rota_UsuarioResponse Rota_Usuario(Agent_SSO.ServiceReference2.Rota_UsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Autenticacao_UsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Autenticacao_Usuario", Namespace="http://tempuri.org/", Order=0)]
        public Agent_SSO.ServiceReference2.Autenticacao_UsuarioRequestBody Body;
        
        public Autenticacao_UsuarioRequest() {
        }
        
        public Autenticacao_UsuarioRequest(Agent_SSO.ServiceReference2.Autenticacao_UsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Autenticacao_UsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPassword;
        
        public Autenticacao_UsuarioRequestBody() {
        }
        
        public Autenticacao_UsuarioRequestBody(string sUser, string sPassword) {
            this.sUser = sUser;
            this.sPassword = sPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Autenticacao_UsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Autenticacao_UsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public Agent_SSO.ServiceReference2.Autenticacao_UsuarioResponseBody Body;
        
        public Autenticacao_UsuarioResponse() {
        }
        
        public Autenticacao_UsuarioResponse(Agent_SSO.ServiceReference2.Autenticacao_UsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Autenticacao_UsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Autenticacao_UsuarioResult;
        
        public Autenticacao_UsuarioResponseBody() {
        }
        
        public Autenticacao_UsuarioResponseBody(string Autenticacao_UsuarioResult) {
            this.Autenticacao_UsuarioResult = Autenticacao_UsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Registra_Tempo_UsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Registra_Tempo_Usuario", Namespace="http://tempuri.org/", Order=0)]
        public Agent_SSO.ServiceReference2.Registra_Tempo_UsuarioRequestBody Body;
        
        public Registra_Tempo_UsuarioRequest() {
        }
        
        public Registra_Tempo_UsuarioRequest(Agent_SSO.ServiceReference2.Registra_Tempo_UsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Registra_Tempo_UsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sCommand;
        
        public Registra_Tempo_UsuarioRequestBody() {
        }
        
        public Registra_Tempo_UsuarioRequestBody(string sCommand) {
            this.sCommand = sCommand;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Registra_Tempo_UsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Registra_Tempo_UsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public Agent_SSO.ServiceReference2.Registra_Tempo_UsuarioResponseBody Body;
        
        public Registra_Tempo_UsuarioResponse() {
        }
        
        public Registra_Tempo_UsuarioResponse(Agent_SSO.ServiceReference2.Registra_Tempo_UsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Registra_Tempo_UsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Registra_Tempo_UsuarioResult;
        
        public Registra_Tempo_UsuarioResponseBody() {
        }
        
        public Registra_Tempo_UsuarioResponseBody(string Registra_Tempo_UsuarioResult) {
            this.Registra_Tempo_UsuarioResult = Registra_Tempo_UsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CriptografiaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Criptografia", Namespace="http://tempuri.org/", Order=0)]
        public Agent_SSO.ServiceReference2.CriptografiaRequestBody Body;
        
        public CriptografiaRequest() {
        }
        
        public CriptografiaRequest(Agent_SSO.ServiceReference2.CriptografiaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CriptografiaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sCommand;
        
        public CriptografiaRequestBody() {
        }
        
        public CriptografiaRequestBody(string sText, string sCommand) {
            this.sText = sText;
            this.sCommand = sCommand;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CriptografiaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CriptografiaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Agent_SSO.ServiceReference2.CriptografiaResponseBody Body;
        
        public CriptografiaResponse() {
        }
        
        public CriptografiaResponse(Agent_SSO.ServiceReference2.CriptografiaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CriptografiaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CriptografiaResult;
        
        public CriptografiaResponseBody() {
        }
        
        public CriptografiaResponseBody(string CriptografiaResult) {
            this.CriptografiaResult = CriptografiaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ping_Localizacao_UsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ping_Localizacao_Usuario", Namespace="http://tempuri.org/", Order=0)]
        public Agent_SSO.ServiceReference2.Ping_Localizacao_UsuarioRequestBody Body;
        
        public Ping_Localizacao_UsuarioRequest() {
        }
        
        public Ping_Localizacao_UsuarioRequest(Agent_SSO.ServiceReference2.Ping_Localizacao_UsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Ping_Localizacao_UsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sCommand;
        
        public Ping_Localizacao_UsuarioRequestBody() {
        }
        
        public Ping_Localizacao_UsuarioRequestBody(string sCommand) {
            this.sCommand = sCommand;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ping_Localizacao_UsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ping_Localizacao_UsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public Agent_SSO.ServiceReference2.Ping_Localizacao_UsuarioResponseBody Body;
        
        public Ping_Localizacao_UsuarioResponse() {
        }
        
        public Ping_Localizacao_UsuarioResponse(Agent_SSO.ServiceReference2.Ping_Localizacao_UsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Ping_Localizacao_UsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Ping_Localizacao_UsuarioResult;
        
        public Ping_Localizacao_UsuarioResponseBody() {
        }
        
        public Ping_Localizacao_UsuarioResponseBody(string Ping_Localizacao_UsuarioResult) {
            this.Ping_Localizacao_UsuarioResult = Ping_Localizacao_UsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Rel_Tempo_UsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Rel_Tempo_Usuario", Namespace="http://tempuri.org/", Order=0)]
        public Agent_SSO.ServiceReference2.Rel_Tempo_UsuarioRequestBody Body;
        
        public Rel_Tempo_UsuarioRequest() {
        }
        
        public Rel_Tempo_UsuarioRequest(Agent_SSO.ServiceReference2.Rel_Tempo_UsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Rel_Tempo_UsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sCommand;
        
        public Rel_Tempo_UsuarioRequestBody() {
        }
        
        public Rel_Tempo_UsuarioRequestBody(string sCommand) {
            this.sCommand = sCommand;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Rel_Tempo_UsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Rel_Tempo_UsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public Agent_SSO.ServiceReference2.Rel_Tempo_UsuarioResponseBody Body;
        
        public Rel_Tempo_UsuarioResponse() {
        }
        
        public Rel_Tempo_UsuarioResponse(Agent_SSO.ServiceReference2.Rel_Tempo_UsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Rel_Tempo_UsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Rel_Tempo_UsuarioResult;
        
        public Rel_Tempo_UsuarioResponseBody() {
        }
        
        public Rel_Tempo_UsuarioResponseBody(string Rel_Tempo_UsuarioResult) {
            this.Rel_Tempo_UsuarioResult = Rel_Tempo_UsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Rota_UsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Rota_Usuario", Namespace="http://tempuri.org/", Order=0)]
        public Agent_SSO.ServiceReference2.Rota_UsuarioRequestBody Body;
        
        public Rota_UsuarioRequest() {
        }
        
        public Rota_UsuarioRequest(Agent_SSO.ServiceReference2.Rota_UsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Rota_UsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sCommand;
        
        public Rota_UsuarioRequestBody() {
        }
        
        public Rota_UsuarioRequestBody(string sCommand) {
            this.sCommand = sCommand;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Rota_UsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Rota_UsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public Agent_SSO.ServiceReference2.Rota_UsuarioResponseBody Body;
        
        public Rota_UsuarioResponse() {
        }
        
        public Rota_UsuarioResponse(Agent_SSO.ServiceReference2.Rota_UsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Rota_UsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Rota_UsuarioResult;
        
        public Rota_UsuarioResponseBody() {
        }
        
        public Rota_UsuarioResponseBody(string Rota_UsuarioResult) {
            this.Rota_UsuarioResult = Rota_UsuarioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_BCC_Autenticacao_UsuarioSoapChannel : Agent_SSO.ServiceReference2.WS_BCC_Autenticacao_UsuarioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_BCC_Autenticacao_UsuarioSoapClient : System.ServiceModel.ClientBase<Agent_SSO.ServiceReference2.WS_BCC_Autenticacao_UsuarioSoap>, Agent_SSO.ServiceReference2.WS_BCC_Autenticacao_UsuarioSoap {
        
        public WS_BCC_Autenticacao_UsuarioSoapClient() {
        }
        
        public WS_BCC_Autenticacao_UsuarioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_BCC_Autenticacao_UsuarioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_BCC_Autenticacao_UsuarioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_BCC_Autenticacao_UsuarioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_SSO.ServiceReference2.Autenticacao_UsuarioResponse Agent_SSO.ServiceReference2.WS_BCC_Autenticacao_UsuarioSoap.Autenticacao_Usuario(Agent_SSO.ServiceReference2.Autenticacao_UsuarioRequest request) {
            return base.Channel.Autenticacao_Usuario(request);
        }
        
        public string Autenticacao_Usuario(string sUser, string sPassword) {
            Agent_SSO.ServiceReference2.Autenticacao_UsuarioRequest inValue = new Agent_SSO.ServiceReference2.Autenticacao_UsuarioRequest();
            inValue.Body = new Agent_SSO.ServiceReference2.Autenticacao_UsuarioRequestBody();
            inValue.Body.sUser = sUser;
            inValue.Body.sPassword = sPassword;
            Agent_SSO.ServiceReference2.Autenticacao_UsuarioResponse retVal = ((Agent_SSO.ServiceReference2.WS_BCC_Autenticacao_UsuarioSoap)(this)).Autenticacao_Usuario(inValue);
            return retVal.Body.Autenticacao_UsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_SSO.ServiceReference2.Registra_Tempo_UsuarioResponse Agent_SSO.ServiceReference2.WS_BCC_Autenticacao_UsuarioSoap.Registra_Tempo_Usuario(Agent_SSO.ServiceReference2.Registra_Tempo_UsuarioRequest request) {
            return base.Channel.Registra_Tempo_Usuario(request);
        }
        
        public string Registra_Tempo_Usuario(string sCommand) {
            Agent_SSO.ServiceReference2.Registra_Tempo_UsuarioRequest inValue = new Agent_SSO.ServiceReference2.Registra_Tempo_UsuarioRequest();
            inValue.Body = new Agent_SSO.ServiceReference2.Registra_Tempo_UsuarioRequestBody();
            inValue.Body.sCommand = sCommand;
            Agent_SSO.ServiceReference2.Registra_Tempo_UsuarioResponse retVal = ((Agent_SSO.ServiceReference2.WS_BCC_Autenticacao_UsuarioSoap)(this)).Registra_Tempo_Usuario(inValue);
            return retVal.Body.Registra_Tempo_UsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_SSO.ServiceReference2.CriptografiaResponse Agent_SSO.ServiceReference2.WS_BCC_Autenticacao_UsuarioSoap.Criptografia(Agent_SSO.ServiceReference2.CriptografiaRequest request) {
            return base.Channel.Criptografia(request);
        }
        
        public string Criptografia(string sText, string sCommand) {
            Agent_SSO.ServiceReference2.CriptografiaRequest inValue = new Agent_SSO.ServiceReference2.CriptografiaRequest();
            inValue.Body = new Agent_SSO.ServiceReference2.CriptografiaRequestBody();
            inValue.Body.sText = sText;
            inValue.Body.sCommand = sCommand;
            Agent_SSO.ServiceReference2.CriptografiaResponse retVal = ((Agent_SSO.ServiceReference2.WS_BCC_Autenticacao_UsuarioSoap)(this)).Criptografia(inValue);
            return retVal.Body.CriptografiaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_SSO.ServiceReference2.Ping_Localizacao_UsuarioResponse Agent_SSO.ServiceReference2.WS_BCC_Autenticacao_UsuarioSoap.Ping_Localizacao_Usuario(Agent_SSO.ServiceReference2.Ping_Localizacao_UsuarioRequest request) {
            return base.Channel.Ping_Localizacao_Usuario(request);
        }
        
        public string Ping_Localizacao_Usuario(string sCommand) {
            Agent_SSO.ServiceReference2.Ping_Localizacao_UsuarioRequest inValue = new Agent_SSO.ServiceReference2.Ping_Localizacao_UsuarioRequest();
            inValue.Body = new Agent_SSO.ServiceReference2.Ping_Localizacao_UsuarioRequestBody();
            inValue.Body.sCommand = sCommand;
            Agent_SSO.ServiceReference2.Ping_Localizacao_UsuarioResponse retVal = ((Agent_SSO.ServiceReference2.WS_BCC_Autenticacao_UsuarioSoap)(this)).Ping_Localizacao_Usuario(inValue);
            return retVal.Body.Ping_Localizacao_UsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_SSO.ServiceReference2.Rel_Tempo_UsuarioResponse Agent_SSO.ServiceReference2.WS_BCC_Autenticacao_UsuarioSoap.Rel_Tempo_Usuario(Agent_SSO.ServiceReference2.Rel_Tempo_UsuarioRequest request) {
            return base.Channel.Rel_Tempo_Usuario(request);
        }
        
        public string Rel_Tempo_Usuario(string sCommand) {
            Agent_SSO.ServiceReference2.Rel_Tempo_UsuarioRequest inValue = new Agent_SSO.ServiceReference2.Rel_Tempo_UsuarioRequest();
            inValue.Body = new Agent_SSO.ServiceReference2.Rel_Tempo_UsuarioRequestBody();
            inValue.Body.sCommand = sCommand;
            Agent_SSO.ServiceReference2.Rel_Tempo_UsuarioResponse retVal = ((Agent_SSO.ServiceReference2.WS_BCC_Autenticacao_UsuarioSoap)(this)).Rel_Tempo_Usuario(inValue);
            return retVal.Body.Rel_Tempo_UsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_SSO.ServiceReference2.Rota_UsuarioResponse Agent_SSO.ServiceReference2.WS_BCC_Autenticacao_UsuarioSoap.Rota_Usuario(Agent_SSO.ServiceReference2.Rota_UsuarioRequest request) {
            return base.Channel.Rota_Usuario(request);
        }
        
        public string Rota_Usuario(string sCommand) {
            Agent_SSO.ServiceReference2.Rota_UsuarioRequest inValue = new Agent_SSO.ServiceReference2.Rota_UsuarioRequest();
            inValue.Body = new Agent_SSO.ServiceReference2.Rota_UsuarioRequestBody();
            inValue.Body.sCommand = sCommand;
            Agent_SSO.ServiceReference2.Rota_UsuarioResponse retVal = ((Agent_SSO.ServiceReference2.WS_BCC_Autenticacao_UsuarioSoap)(this)).Rota_Usuario(inValue);
            return retVal.Body.Rota_UsuarioResult;
        }
    }
}
